CREATE TABLE _user (
  id       INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 3),
  user_id  UUID,
  kyc_done BOOLEAN
);

CREATE TABLE team (
  id        SMALLINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 3),
  team_name TEXT NOT NULL,
  logo      TEXT
);

CREATE TABLE player (
  id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 6),
  first_name TEXT NOT NULL,
  last_name  TEXT NOT NULL
);

CREATE TABLE match (
  id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 7),
  team1_id   SMALLINT NOT NULL REFERENCES team (id),
  team2_id   SMALLINT NOT NULL REFERENCES team (id),
  live       BOOLEAN NOT NULL DEFAULT FALSE,
  start_time TIMESTAMP NOT NULL,
  league     TEXT
);

CREATE TABLE squad (
  team_id   SMALLINT NOT NULL REFERENCES team (id),
  player_id INTEGER NOT NULL REFERENCES player (id)
);

CREATE TABLE ball_by_ball_score (
  match_id     INTEGER NOT NULL REFERENCES match (id),
  batter       INTEGER NOT NULL REFERENCES player (id),
  bowler       INTEGER NOT NULL REFERENCES player (id),
  ball         NUMERIC(4, 1) NOT NULL,
  teamid       SMALLINT NOT NULL,
  runs_off_bat SMALLINT,
  extra        SMALLINT,
  wide         SMALLINT,
  noball       SMALLINT,
  bye          SMALLINT,
  legbye       SMALLINT,
  penalty      SMALLINT,
  wicket       BOOLEAN,
  six          BOOLEAN,
  four         BOOLEAN,
  commentary   TEXT
);

CREATE TABLE lobby (
  id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 5),
  title         TEXT NOT NULL,
  price         SMALLINT NOT NULL,
  match_id      INTEGER NOT NULL REFERENCES match (id),
  playing_count INTEGER DEFAULT 0
);

CREATE TYPE ticket_types AS ENUM ('batting', 'bowling', 'overall');

CREATE TABLE ticket (
  id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 3),
  match_id       INTEGER NOT NULL REFERENCES match (id),
  team1_id       SMALLINT NOT NULL REFERENCES team (id),
  team2_id       SMALLINT NOT NULL REFERENCES team (id),
  user_id        INTEGER NOT NULL REFERENCES _user (id),
  ticket_type    TICKET_TYPES NOT NULL,
  ticket_price   SMALLINT NOT NULL,
  total_bet      SMALLINT NOT NULL,
  transaction_id TEXT,
  pay_confirmed  BOOLEAN
);

CREATE TYPE bet_type AS ENUM (
  'batterRun', 'runRate', 'bowlerRun', 'wicket', 'economy', 'teamRun', 'boundaries'
);

CREATE TABLE bet_price (
  match_id     SMALLINT NOT NULL REFERENCES match (id),
  price        SMALLINT NOT NULL,
  commission   SMALLINT NOT NULL,
  ticket_types TICKET_TYPES,
  bet_type     BET_TYPE
);

CREATE TABLE bet (
  ticket_id SMALLINT NOT NULL REFERENCES ticket (id),
  bet       SMALLINT NOT NULL, -- For storing runs, wickets, etc. bet by user
  bet_type  BET_TYPE,
  player_id INTEGER
);
